version: '3.7'

services:

#  ubuntu:
#    image: ubuntu:latest
#    command: "tail -f /dev/null"

  weather-app:
    image: spring-boot-open-weather-th
    restart: always
    build: .
    volumes:
      - mysql-data:/data/springboot-docker-compose-app
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_DB: weather_db
    command: bash -c "/usr/wait-for-it.sh --timeout=0 mysql:3306"

  mysql:
    image: mysql:8.0.19
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: weather_db


volumes:
  mysql-data: